from django.urls import path

from . import api_views, page_views


urlpatterns = [
    path("", page_views.login_page),
    path("login", page_views.login_page),
    path("logout", page_views.logout_page),
    path("projects", page_views.projects_page),
    path("projects/<int:id>", page_views.project_detail_page),
    path("sections/<int:id>", page_views.section_detail_page),
    path("test-suite/<int:id>", page_views.test_suite_detail_page),
    path("project-qa", page_views.project_qa_page),
    path("project-qa/<int:id>", page_views.project_qa_detail_page),
    path("project-qa/<int:project_id>/test-runs", page_views.test_runs_page),
    path("project/<int:project_id>/test-runs", page_views.test_runs_page),
    path("test-run/<int:id>", page_views.test_run_detail_page),
    path("project/<int:project_id>/traceability-matrix", page_views.traceability_matrix_page),
    path("admin/users", page_views.admin_users_page),
    path("admin/ai-settings", page_views.admin_ai_settings_page),
    path("admin/ai-activity", page_views.admin_ai_activity_page),
    path("admin/project-integrations", page_views.admin_project_integrations_page),
    path("admin/users/<int:id>/activate", page_views.admin_user_activate),
    path("admin/users/<int:id>/deactivate", page_views.admin_user_deactivate),
    path("api/admin/ai-settings/test-connection", api_views.admin_ai_test_connection),
    path("api/projects", api_views.projects_collection),
    path("api/projects/<int:id>", api_views.projects_item),
    path("api/projects/<int:project_id>/test-suites", api_views.project_test_suites_collection),
    path("api/projects/<int:project_id>/test-suites/search", api_views.project_test_suites_search),
    path("api/projects/<int:project_id>/test-cases", api_views.project_cases),
    path("api/projects/<int:project_id>/sections", api_views.project_sections_collection),
    path("api/projects/<int:project_id>/sections/import", api_views.project_sections_import),
    path("api/projects/<int:project_id>/user-stories", api_views.project_user_stories),
    path("api/projects/<int:project_id>/tags", api_views.project_tags_collection),
    path("api/projects/<int:project_id>/test-runs", api_views.project_test_runs_collection),
    path("api/projects/<int:project_id>/test-runs/search", api_views.test_runs_search),
    path("api/projects/<int:project_id>/traceability-ai-quality", api_views.traceability_ai_quality),
    path("api/projects/<int:project_id>/traceability-matrix/export-excel", api_views.traceability_matrix_export_excel),
    path("api/test-suites/<int:id>", api_views.test_suite_item),
    path("api/test-suites/<int:test_suite_id>/test-cases", api_views.test_suite_cases_collection),
    path("api/test-suites/<int:test_suite_id>/test-cases/search", api_views.test_suite_cases_search),
    path("api/test-suites/<int:test_suite_id>/import-test-cases", api_views.import_test_cases_external),
    path("api/test-suites/<int:test_suite_id>/ai-analysis", api_views.ai_analysis_run),
    path("api/test-suites/<int:test_suite_id>/ai-test-case-review", api_views.ai_review_suite),
    path("api/test-suites/<int:test_suite_id>/ai-test-case-review/next", api_views.ai_review_suite_queue_next),
    path("api/test-suites/<int:test_suite_id>/ai-test-case-review/status", api_views.ai_review_suite_queue_status),
    path("api/test-suites/<int:test_suite_id>/ai-reviews", api_views.ai_review_suite_get),
    path("api/test-cases/<int:id>", api_views.test_case_item),
    path("api/test-cases/<int:id>/clone", api_views.test_case_clone),
    path("api/test-cases/<int:test_case_id>/tags/<int:tag_id>", api_views.test_case_tag_item),
    path("api/test-cases/<int:test_case_id>/steps", api_views.test_case_add_step),
    path("api/test-steps/<int:step_id>", api_views.test_step_item),
    path("api/test-cases/<int:test_case_id>/user-stories/<int:user_story_id>", api_views.test_case_user_story_item),
    path("api/sections/<int:id>", api_views.section_item),
    path("api/sections/<int:id>/delete-with-user-stories", api_views.section_delete_with_user_stories),
    path("api/sections/<int:section_id>/user-stories", api_views.section_user_stories_collection),
    path("api/sections/<int:section_id>/user-stories/import", api_views.section_user_stories_import),
    path("api/user-stories/<int:id>", api_views.user_story_item),
    path("api/tags/<int:id>", api_views.tag_item),
    path("api/comments", api_views.comments_create),
    path("api/comments/<int:comment_id>", api_views.comment_item),
    path("api/comments/test-case/<int:test_case_id>", api_views.comments_by_test_case),
    path("api/comments/ai/<int:test_case_id>", api_views.comments_ai_create),
    path("admin/users/api", api_views.users_collection),
    path("admin/users/api/<int:id>", api_views.user_item),
    path("admin/users/api/<int:id>/deactivate", api_views.users_deactivate),
    path("admin/users/api/<int:id>/activate", api_views.users_activate),
    path("admin/users/api/search", api_views.users_search),
    path("api/test-runs/<int:id>/detailed", api_views.test_run_detailed),
    path("api/test-runs/<int:id>/statistics", api_views.test_run_statistics),
    path("api/test-runs/<int:id>", api_views.test_run_item),
    path("api/test-runs/<int:id>/status", api_views.test_run_status_update),
    path("api/test-runs/<int:test_run_id>/test-cases/<int:test_case_id>", api_views.test_run_test_case_status_update),
    path("api/test-cases/<int:test_case_id>/ai-review", api_views.test_case_ai_review_item),
    path("api/token/status", api_views.token_status),
    path("api/token/refresh", api_views.token_refresh),
]
